# Generated by Django 3.2.11 on 2024-03-29 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppMessage',
            fields=[
                ('dt_created', models.DateTimeField(auto_created=True)),
                ('content', models.CharField(max_length=512)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to='users.profile')),
                ('sender_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile', to='users.profile')),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
    ]
