# Generated by Django 3.2.11 on 2024-05-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappmessage',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
